### ISSUE TITLE
Variables globales

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto-dellping#10]
Como se indica en las condiciones del trabajo, no se pueden usar variables globales:

https://github.com/aigora/twIE_2021-proyecto-dellping/blob/3283d5108426651ad6782eee0a2ec829607b944a/beta.c#L5-L11

Todas las variables deben estar definidas dentro de main o de las funciones.

**Comment by lucasceezar** [comment]
Pero entonces, si el programa lee un dato dentro de la funcion main y se lo asigna a una variable definida en main, luego no puedo utilizar ese dato en otra funcion, ¿no?

**Comment by oscarperpinan** [comment]
Sí, claro que se puede, pero se lo debe pasar a través de un argumento, ya sea con paso por valor o con paso por referencia (punteros).

**Comment by lucasceezar** [comment]
Estoy en proceso de quitar las variables globales que utilizamos en el código (las usamos sin saber que nos referíamos a ellas al hablar de variables globales ':( ) así que aun no puedo cerrar la issues, cosa que intentaré acabar de corregir durante las primeras horas de la tarde de hoy, y si no lo consigo , a lo largo del fin de semana. La segunda issue que nos abriste por el uso de system("cls") tambien la corregiré pero al ser un problema menor, lo dejo para cuando esté resuelto el problemas de las variables. Gracias.

**Comment by lucasceezar** [comment]
Igual podríamos intentar cuadrar una tutoría si es posible, porque me está suponiendo algunas dificultades el reestructurar el código para introducir las variables en otro formato, de manera que las diferentes funciones del programa puedan interactuar con ellas.

**Comment by oscarperpinan** [comment]
De acuerdo. Si el lunes no habéis conseguido resolverlo, escribid un mensaje por el canal de tutorías o un correo electrónico y organizamos una reunión.
