### ISSUE TITLE
Uso de system

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto-dellping#11]
La función `system` pertenece a la librería `stdlib.h`, que no habéis declarado al principio con una directiva `include`. Por otra parte, debéis evitar su uso porque hace llamadas a comandos del sistema operativo y, por tanto, no es portable: lo que funciona en windows no funciona en linux o mac, y viceversa.

https://github.com/aigora/twIE_2021-proyecto-dellping/blob/3283d5108426651ad6782eee0a2ec829607b944a/beta.c#L56

**Comment by lucasceezar** [comment]
En ese caso, ¿de que otro modo podemos hacer para limpiar la pantalla del programa cuando metamos un nuevo dato o se actualice la pantalla para no llenar la pantalla cada vez de nuevo?

**Comment by oscarperpinan** [comment]
Una solución sencilla es emplear los _ANSI escape codes_. Hablé de ellos en [una respuesta en el canal de tutorías](https://teams.microsoft.com/l/message/19:98e916bb4a3a46a6ac3150257541425d@thread.tacv2/1615334973963?tenantId=6afea85d-c323-4270-b69d-a4fb3927c254&groupId=3477ddd6-cbb2-4bb5-ad31-ecefaebf2091&parentMessageId=1615327042869&teamName=Inform%C3%A1tica%2056IE%20(2020-21)&channelName=Tutor%C3%ADas&createdTime=1615334973963). Probad con:
`printf("\033[2J");`

No olvidéis que necesitaréis [Windows Terminal](https://github.com/microsoft/terminal#installing-and-running-windows-terminal).
