### ISSUE TITLE
Diagrama de flujo

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIE_2021-proyecto-dellping#3]
Debéis crear un fichero en formato [PDF](https://help.github.com/en/articles/rendering-pdf-documents), [GIF, JPEG o PNG](https://help.github.com/en/articles/rendering-and-diffing-images) (**no se admiten documentos Word o similar**) representando el [diagrama de flujo](https://es.wikipedia.org/wiki/Diagrama_de_flujo) previsto para vuestro programa. 
En el punto de inicio tenéis un [tutorial](https://github.com/aigora/punto_inicio/wiki/6.1-C%C3%B3mo-realizar-un-diagrama-de-flujo) para crear diagramas de flujo.
Este diagrama os servirá de guía para la implementación del trabajo. No obstante, ésta será la primera versión, por lo que según vayáis avanzando en el desarrollo del programa podréis y deberéis modificarlo.

**Comment by lucasceezar** [comment]
[Diagrama_flujo_proyectoDellping.pdf](https://github.com/aigora/twIE_2021-proyecto-dellping/files/6280221/Diagrama_flujo_proyectoDellping.pdf)

**Comment by oscarperpinan** [comment]
El diagrama debe estar en un fichero dentro del repositorio.

**Comment by lquintanac** [comment]
Hola buenas, como ya tenéis subido el archivo del diagrama de flujo por tanto cerrar esta issue, Recordad cerrar también la milestone Alpha una vez completada.

**Comment by orgynmobs** [comment]
Acordaos de cerrar la issue , y la milestone si esta está al 100%

**Comment by lucasceezar** [comment]
No entiendo cual es el problema, subí el fichero del diagrama al repositorio principal, donde también está la versión alpha y por si acaso, también aquí. Gracias
